---
# Creating the service

- name: Create env directory
  become: true
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ service_name }}.service.d/"
    state: directory

- name: Create service file
  become: true
  ansible.builtin.template:
    src: "{{ service_name }}.service.j2"
    dest: "/etc/systemd/system/{{ service_name }}.service"

- name: Creates the override.conf file
  become: true
  ansible.builtin.template:
    src: override.conf.j2
    dest: "/etc/systemd/system/{{ service_name }}.service.d/override.conf"

- name: Start docker at boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    masked: false
    name: docker
    state: started

- name: Start weighttracker-db service
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    masked: false
    name: "{{ service_name }}"
    state: started
