---
- name: install docker.io 
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600 
    install_recommends: false 
    name:
     - docker.io
    state: present
    update_cache: true
  register: apt_action
  retries: 100
  until: apt_action is success or ('Failed to lock apt for exclusive operation' not in apt_action.msg and '/var/lib/dpkg/lock' not in apt_action.msg)
